# Generated by Django 5.1 on 2024-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMR', '0004_alter_student_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.IntegerField(),
        ),
    ]
