# Generated by Django 5.1 on 2024-09-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMR', '0005_alter_student_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_contact',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ReportCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report_card_generation', models.DateField(auto_created=True)),
                ('student_rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcards', to='OMR.student')),
            ],
        ),
    ]
